/* Nash push/fold solver (chip EV, no antes, blinds 0.5/1, equal stacks).
 *
 * Computes first-in shove ranges for UTG/MP/CO/BTN/SB and call-a-shove
 * ranges for every seat behind, at stacks 2–25 bb, by fictitious play
 * over the pinned 169×169 preflop equity matrix
 * (scripts/golden/equity_matrix.json, generated by poker-core's
 * `equity_matrix` example).
 *
 * Model simplifications (documented in-app):
 *  - first-caller-takes-it-heads-up: overcalls are ignored;
 *  - label-level ranges: card-removal (blocker) effects on opponents'
 *    holding frequencies are ignored;
 *  - chip EV (no ICM), no antes.
 * These match the classic published jam/fold tables' assumptions.
 *
 * Writes src/data/pushfold.ts. Run:
 *   node --experimental-transform-types scripts/pushfold_gen.ts
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";

type Pos = "UTG" | "MP" | "CO" | "BTN" | "SB" | "BB";

const { labels, equity } = JSON.parse(
  readFileSync(new URL("./golden/equity_matrix.json", import.meta.url), "utf8"),
) as { labels: string[]; equity: number[][] };

const N = 169;
const E = new Float64Array(N * N);
for (let i = 0; i < N; i++) for (let j = 0; j < N; j++) E[i * N + j] = equity[i][j];

// Combo weight of each label (pairs 6, suited 4, offsuit 12) / 1326.
const W = new Float64Array(N);
labels.forEach((l, i) => {
  W[i] = (l.length === 2 ? 6 : l.endsWith("s") ? 4 : 12) / 1326;
});

const SEATS_BEHIND: Record<string, Pos[]> = {
  UTG: ["MP", "CO", "BTN", "SB", "BB"],
  MP: ["CO", "BTN", "SB", "BB"],
  CO: ["BTN", "SB", "BB"],
  BTN: ["SB", "BB"],
  SB: ["BB"],
};
const SHOVER_POSITIONS: Pos[] = ["UTG", "MP", "CO", "BTN", "SB"];
const STACKS = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 22, 25];

const blind = (p: Pos) => (p === "SB" ? 0.5 : p === "BB" ? 1 : 0);

/** ē[h] = Σ_l strat[l]·W[l]·E[h][l], plus the range's total weight. */
function weightedEquity(strat: Float64Array): { vec: Float64Array; mass: number } {
  const vec = new Float64Array(N);
  let mass = 0;
  for (let l = 0; l < N; l++) {
    const m = strat[l] * W[l];
    if (m === 0) continue;
    mass += m;
    for (let h = 0; h < N; h++) vec[h] += m * E[h * N + l];
  }
  return { vec, mass };
}

function solveStack(S: number) {
  // Strategy state: running fictitious-play averages.
  const shove: Record<string, Float64Array> = {};
  const call: Record<string, Float64Array> = {}; // key `${shover}>${caller}`
  // Init: shove top-ish hands, callers tight (vs-random strength order).
  const strength = new Float64Array(N);
  for (let h = 0; h < N; h++) {
    let s = 0;
    for (let l = 0; l < N; l++) s += W[l] * E[h * N + l];
    strength[h] = s;
  }
  const order = [...Array(N).keys()].sort((a, b) => strength[b] - strength[a]);
  for (const p of SHOVER_POSITIONS) {
    shove[p] = new Float64Array(N);
    order.slice(0, 50).forEach((h) => (shove[p][h] = 1));
    for (const c of SEATS_BEHIND[p]) {
      call[`${p}>${c}`] = new Float64Array(N);
      order.slice(0, 15).forEach((h) => (call[`${p}>${c}`][h] = 1));
    }
  }

  const ROUNDS = 200;
  for (let t = 1; t <= ROUNDS; t++) {
    // --- Shover best responses vs current average calling ranges ---
    for (const p of SHOVER_POSITIONS) {
      const behind = SEATS_BEHIND[p];
      const callers = behind.map((c) => {
        const { vec, mass } = weightedEquity(call[`${p}>${c}`]);
        const dead = (c !== "SB" && p !== "SB" ? 0.5 : 0) + (c !== "BB" ? 1 : 0);
        return { pos: c, vec, mass, pot: 2 * S + dead };
      });
      const bP = blind(p);
      const br = new Float64Array(N);
      for (let h = 0; h < N; h++) {
        let pAllFold = 1;
        let ev = 0;
        for (const c of callers) {
          const pCall = c.mass;
          const eq = pCall > 0 ? c.vec[h] / pCall : 0.5;
          ev += pAllFold * pCall * (eq * c.pot - (S - bP));
          pAllFold *= 1 - pCall;
        }
        ev += pAllFold * 1.5;
        br[h] = ev > 0 ? 1 : 0;
      }
      for (let h = 0; h < N; h++) shove[p][h] += (br[h] - shove[p][h]) / t;
    }
    // --- Caller best responses vs current average shove ranges ---
    for (const p of SHOVER_POSITIONS) {
      const { vec, mass } = weightedEquity(shove[p]);
      for (const c of SEATS_BEHIND[p]) {
        const dead = (c !== "SB" && p !== "SB" ? 0.5 : 0) + (c !== "BB" ? 1 : 0);
        const pot = 2 * S + dead;
        const bC = blind(c);
        const key = `${p}>${c}`;
        for (let h = 0; h < N; h++) {
          const eq = mass > 0 ? vec[h] / mass : 0.5;
          const br = eq * pot - (S - bC) > 0 ? 1 : 0;
          call[key][h] += (br - call[key][h]) / t;
        }
      }
    }
  }
  return { shove, call };
}

/** Sparse, rounded output: {label: weight} with 0-weights omitted. */
function sparse(strat: Float64Array): Record<string, number> {
  const out: Record<string, number> = {};
  for (let h = 0; h < N; h++) {
    let w = strat[h];
    if (w < 0.05) continue;
    w = w > 0.95 ? 1 : Math.round(w * 100) / 100;
    out[labels[h]] = w;
  }
  return out;
}

const shoveOut: Record<number, Partial<Record<Pos, Record<string, number>>>> = {};
const callOut: Record<number, Record<string, Record<string, number>>> = {};
for (const S of STACKS) {
  const { shove, call } = solveStack(S);
  shoveOut[S] = {};
  callOut[S] = {};
  for (const p of SHOVER_POSITIONS) shoveOut[S][p] = sparse(shove[p]);
  for (const key of Object.keys(call)) callOut[S][key] = sparse(call[key]);
  const width = (r: Record<string, number>) =>
    Object.entries(r).reduce((a, [l, w]) => a + w * (l.length === 2 ? 6 : l.endsWith("s") ? 4 : 12), 0) / 1326;
  console.log(
    `S=${S}bb  SB jam ${(width(shoveOut[S].SB!) * 100).toFixed(1)}%  BTN jam ${(width(shoveOut[S].BTN!) * 100).toFixed(1)}%  BB call vs SB ${(width(callOut[S]["SB>BB"]) * 100).toFixed(1)}%`,
  );
}

const dir = fileURLToPath(new URL("../src/data/", import.meta.url));
mkdirSync(dir, { recursive: true });
const banner = `/* AUTO-GENERATED by scripts/pushfold_gen.ts — do not edit by hand.
 * Nash push/fold equilibrium (chip EV, no antes, first-caller model,
 * label-level ranges), solved by fictitious play over the pinned
 * preflop equity matrix. Weights are shove/call frequencies 0..1.
 */
`;
writeFileSync(
  dir + "pushfold.ts",
  banner +
    `export type PushFoldPos = "UTG" | "MP" | "CO" | "BTN" | "SB";\n` +
    `export const PUSHFOLD_STACKS = ${JSON.stringify(STACKS)} as const;\n` +
    `/** shove[stack][pos] -> {label: frequency} */\n` +
    `export const NASH_SHOVE: Record<number, Partial<Record<PushFoldPos, Record<string, number>>>> = ${JSON.stringify(shoveOut)};\n` +
    `/** call[stack]["SHOVER>CALLER"] -> {label: frequency} */\n` +
    `export const NASH_CALL: Record<number, Record<string, Record<string, number>>> = ${JSON.stringify(callOut)};\n`,
);
console.log("wrote src/data/pushfold.ts");
